package com.example.srm.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Represents a Course entity in the Student Result Management System.
 * This class maps to a Firestore document in the 'courses' collection.
 * Uses Lombok annotations to reduce boilerplate code for getters, setters, and constructors.
 */
@Data                   // Lombok: Generates getters, setters, toString(), equals(), and hashCode()
@NoArgsConstructor      // Lombok: Generates a no-argument constructor
@AllArgsConstructor     // Lombok: Generates a constructor with all fields as arguments
public class Course {

    /**
     * Firestore document ID (auto-generated by Firestore).
     * This is the unique identifier for the course document in the database.
     */
    private String id;

    /**
     * Unique course code (e.g., "CS101").
     * Used for quick identification and reference in the system.
     */
    private String courseCode;

    /**
     * Full name of the course (e.g., "Introduction to Computer Science").
     */
    private String courseName;

    /**
     * Name or identifier of the instructor teaching the course.
     * Note: In a future enhancement, this could be replaced with a reference to a Lecturer ID
     * to enable proper relationship mapping between courses and lecturers.
     */
    private String courseInstructor;
}